# Generated by Django 5.2.5 on 2025-10-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
