# Generated by Django 5.2.5 on 2025-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0002_rename_author_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
