# Generated by Django 5.2.5 on 2025-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_page_home"),
        ),
    ]
