# Generated by Django 5.2.5 on 2025-09-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0006_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default="blog_page_home/default.png",
                null=True,
                upload_to="blog_page_home",
            ),
        ),
    ]
