# Generated by Django 5.2.5 on 2025-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0007_alter_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("subject", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254)),
                ("massage", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
