# Generated by Django 5.2.5 on 2025-09-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0008_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
