# Generated by Django 5.2.5 on 2025-09-29 16:24

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0011_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
