# Generated by Django 5.2.5 on 2025-09-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0012_alter_post_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=256)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("approved_by", models.BooleanField(default=False)),
            ],
        ),
    ]
