# Generated by Django 5.2.5 on 2025-09-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0013_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="approved_by",
            new_name="approved",
        ),
    ]
