# Generated by Django 5.2.5 on 2025-09-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0014_rename_approved_by_comment_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="massage",
            field=models.TextField(default=""),
        ),
    ]
