# Generated by Django 5.2.5 on 2025-09-30 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_page", "0015_comment_massage"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog_page.post",
            ),
            preserve_default=False,
        ),
    ]
