# Generated by Django 5.2.5 on 2025-09-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("joined_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
