# Generated by Django 5.2.5 on 2025-09-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0002_newsletter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="created_date",
        ),
    ]
