# Generated by Django 5.2.5 on 2025-09-30 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0003_remove_contact_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
